#!/bin/sh
set -euo pipefail

function noop {
    echo
}
function asis {
    echo $1
}
function camel {
    echo $(snake $1) | awk -F _ '{printf "%s", $1; for(i=2; i<=NF; i++) printf "%s", toupper(substr($i,1,1)) substr($i,2); print"";}'
}
function pascal {
    _tmp="$(camel $1)"
    echo "$(echo ${_tmp:0:1} | tr '[:lower:]' '[:upper:]')${_tmp:1}"
}
function dot {
    echo $(snake $1) | tr '_' '.'
}
function kebab {
    echo $(snake $1) | tr '_' '-'
}
function snake {
    echo $1 | tr '[:upper:]' '[:lower:]'
}

_case=${1:-"asis"}
_format=${2:-'$k=$v'}
_filter=${3:-"PLUGIN_"}

_params=""
#IFS=$'\n'
for _key in $(export | sed -nr 's/export ([A-Z0-9_]+)='"'"'.+/\1/p'); do
    eval "_val=\"\$$_key\""
    case $_key in $_filter*)
        _key=$($_case ${_key#$_filter})
        test "${_val:0:1}" = "$" && eval _val="$_val"
        _params="$_params $(echo "$_format" | k="$_key" v="$_val" envsubst)"
    esac
done

printf "$_params"
# export PLUGIN_AAA="$(cat /etc/issue)"
# export PLUGIN_XXX_YYY='$HOME'
# env2args asis 'export $k='"'"'$v'"'\n"
